import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;


public class FormKonversi extends javax.swing.JFrame {

    /**
     * Creates new form FormKonversi
     */
    public FormKonversi() {
        initComponents();
        setLocationRelativeTo(null);
        
        cmbDari.addItem("Celsius");
        cmbDari.addItem("Fahrenheit");
        cmbDari.addItem("Reamur");
        cmbDari.addItem("Kelvin");

        cmbKe.addItem("Celsius");
        cmbKe.addItem("Fahrenheit");
        cmbKe.addItem("Reamur");
        cmbKe.addItem("Kelvin");
        
        buttonGroup1.add(rdbManual);
        buttonGroup1.add(rdbOtomatis);
        rdbManual.setSelected(true);
    }

private void konversiSuhu() {
    try {
        String teksInput = txtSuhu.getText().trim();
        
        // Cegah error jika kosong atau hanya "-" atau hanya "."
        if (teksInput.isEmpty() || teksInput.equals("-") || teksInput.equals(".") || teksInput.equals("-.")) {
            lblHasil.setText(""); // kosongkan hasil
            return; // keluar tanpa error
        }

        double input = Double.parseDouble(teksInput);
        String dari = cmbDari.getSelectedItem().toString();
        String ke = cmbKe.getSelectedItem().toString();
        double hasil = 0;

        // LOGIKA KONVERSI
        if (dari.equals("Celsius")) {
            switch (ke) {
                case "Fahrenheit": hasil = (input * 9/5) + 32; break;
                case "Reamur": hasil = input * 4/5; break;
                case "Kelvin": hasil = input + 273.15; break;
                default: hasil = input;
            }
        } else if (dari.equals("Fahrenheit")) {
            switch (ke) {
                case "Celsius": hasil = (input - 32) * 5/9; break;
                case "Reamur": hasil = (input - 32) * 4/9; break;
                case "Kelvin": hasil = ((input - 32) * 5/9) + 273.15; break;
                default: hasil = input;
            }
        } else if (dari.equals("Reamur")) {
            switch (ke) {
                case "Celsius": hasil = input * 5/4; break;
                case "Fahrenheit": hasil = (input * 9/4) + 32; break;
                case "Kelvin": hasil = (input * 5/4) + 273.15; break;
                default: hasil = input;
            }
        } else if (dari.equals("Kelvin")) {
            switch (ke) {
                case "Celsius": hasil = input - 273.15; break;
                case "Fahrenheit": hasil = ((input - 273.15) * 9/5) + 32; break;
                case "Reamur": hasil = (input - 273.15) * 4/5; break;
                default: hasil = input;
            }
        }

        lblHasil.setText("Hasil: " + String.format("%.2f", hasil) + " " + ke);

    } catch (NumberFormatException e) {
        lblHasil.setText("Input tidak valid");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblInput = new javax.swing.JLabel();
        txtSuhu = new javax.swing.JTextField();
        rdbManual = new javax.swing.JRadioButton();
        rdbOtomatis = new javax.swing.JRadioButton();
        lblDari = new javax.swing.JLabel();
        lblKe = new javax.swing.JLabel();
        cmbDari = new javax.swing.JComboBox<>();
        cmbKe = new javax.swing.JComboBox<>();
        btnKonversi = new javax.swing.JButton();
        lblHasil = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblJudul.setText("APLIKASI KONVERSI SUHU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblJudul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(lblJudul))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        lblInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInput.setText("MASUKKAN ANGKA");

        txtSuhu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSuhuFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSuhuFocusLost(evt);
            }
        });
        txtSuhu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSuhuKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSuhuKeyTyped(evt);
            }
        });

        rdbManual.setText("MANUAL");
        rdbManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbManualActionPerformed(evt);
            }
        });

        rdbOtomatis.setText("OTOMATIS");
        rdbOtomatis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbOtomatisActionPerformed(evt);
            }
        });

        lblDari.setText("DARI");

        lblKe.setText("KE");

        cmbDari.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDariItemStateChanged(evt);
            }
        });

        cmbKe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbKeItemStateChanged(evt);
            }
        });

        btnKonversi.setText("KONVERSI");
        btnKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonversiActionPerformed(evt);
            }
        });

        lblHasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHasil.setText("jLabel1");

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKeluar.setText("KELUAR");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSuhu)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 78, Short.MAX_VALUE)
                                .addComponent(lblDari)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbDari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(rdbManual)
                                .addGap(12, 12, 12)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblKe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rdbOtomatis)))
                    .addComponent(btnKeluar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKonversi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHasil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(lblInput)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbOtomatis)
                    .addComponent(rdbManual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDari)
                    .addComponent(cmbDari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKe)
                    .addComponent(cmbKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKonversi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHasil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbManualActionPerformed
        // TODO add your handling code here:
        btnKonversi.setEnabled(true);
    }//GEN-LAST:event_rdbManualActionPerformed

    private void btnKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonversiActionPerformed
        // TODO add your handling code here:
        konversiSuhu();
    }//GEN-LAST:event_btnKonversiActionPerformed

    private void txtSuhuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuhuKeyTyped
        // TODO add your handling code here:
    char c = evt.getKeyChar();

    // Izinkan backspace
    if (c == KeyEvent.VK_BACK_SPACE) {
        return;
    }

    // Izinkan angka
    if (Character.isDigit(c)) {
        return;
    }

    // Izinkan titik (.) hanya satu kali
    if (c == '.' && !txtSuhu.getText().contains(".")) {
        return;
    }

    // Izinkan tanda minus (-) hanya di posisi pertama
    if (c == '-' && txtSuhu.getCaretPosition() == 0 && !txtSuhu.getText().contains("-")) {
        return;
    }

    // Jika bukan karakter yang diizinkan, batalkan input
    evt.consume();

    }//GEN-LAST:event_txtSuhuKeyTyped

    private void txtSuhuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuhuKeyReleased
        // TODO add your handling code here:
        if (rdbOtomatis.isSelected()) {
        konversiSuhu();
        }
    }//GEN-LAST:event_txtSuhuKeyReleased

    private void rdbOtomatisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbOtomatisActionPerformed
        // TODO add your handling code here:
        btnKonversi.setEnabled(false);
        konversiSuhu();
    }//GEN-LAST:event_rdbOtomatisActionPerformed

    private void cmbDariItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDariItemStateChanged
        // TODO add your handling code here:
        if (rdbOtomatis.isSelected()) {
        konversiSuhu();
        }
    }//GEN-LAST:event_cmbDariItemStateChanged

    private void cmbKeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbKeItemStateChanged
        // TODO add your handling code here:
        if (rdbOtomatis.isSelected()) {
        konversiSuhu();
        }
    }//GEN-LAST:event_cmbKeItemStateChanged

    private void txtSuhuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSuhuFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuhuFocusLost

    private void txtSuhuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSuhuFocusGained
        // TODO add your handling code here:
        txtSuhu.setText("");
        lblHasil.setText("");
    }//GEN-LAST:event_txtSuhuFocusGained

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        txtSuhu.setText("");
        txtSuhu.requestFocus();
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKonversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKonversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKonversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKonversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKonversi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnKonversi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbDari;
    private javax.swing.JComboBox<String> cmbKe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDari;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JLabel lblInput;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblKe;
    private javax.swing.JRadioButton rdbManual;
    private javax.swing.JRadioButton rdbOtomatis;
    private javax.swing.JTextField txtSuhu;
    // End of variables declaration//GEN-END:variables
}
